//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hastane
    {
       
        [Display(Name = "kimlik numarınız")]
        [Range(1 , 99999999999999, ErrorMessage = "Kimlik numarınızı doğru bir şekide girdirmelisiniz.")]
        public int CustomerID { get; set; }


        [Display(Name = "AD")]
        [Required(ErrorMessage = "Adınızı girdirmelisiniz .")]
        public string FirstName { get; set; }

        [Display(Name = "Soyadınız")]
        [Required(ErrorMessage = "Soyadınızı girdirmelisiniz .")]
        public string LastName { get; set; }

        [Display(Name = "Mail")]
        [Required(ErrorMessage = "Mail Adresinizi girdirmelisiniz .")]
        public string Mail { get; set; }

        [Display(Name = "Tarih")]
        [Required(ErrorMessage = "Lütfen randevu tarihinizi seçin.")]
        public System.DateTime Date { get; set; }

        [Phone]
        [Range(5000000000, 9999999999, ErrorMessage = "numaranızı doğru bir şekilde girdirmelisiniz")]
        [Required(ErrorMessage = "Telefon numaranızı girdirmelisiniz.")]
        public string Telefon { get; set; }

        public string Text { get; set; }
    }
}
